#! /bin/bash

read-p "What would you like to name your wallet?" wallet_name;

apt update;

wget -c https://go.dev/dl/go1.22.0.linux-amd64.tar.gz;

tar -C /usr/local/ -xzf go1.22.0.linux-amd64.tar.gz;

PATH=$PATH:/usr/local/go/bin;

mkdir $HOME/nimble && cd $HOME/nimble;

git clone https://github.com/nimble-technology/wallet-public.git;

cd wallet-public;

make install;

cd;

cd go/bin;

./nimble-networkd keys add $wallet_name;

apt update;

apt install python3-venv;

cd;

cd nimble;

git clone https://github.com/nimble-technology/nimble-miner-public.git;

cd nimble-miner-public;

make install;

source ./nimenv_localminers/bin/activate;
